version: '3.7'

services:
  back:
    build:
      context: ./backend
    command: sh -c "pip install -r requirements.txt && python3 manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8080 project.wsgi"
    expose:
      - 8080
    environment:
      - DEBUG=False
      - SECRET_KEY=DJANGO_SECRET_KEY
  front:
    build:
      context: ./frontend
    command: npm run-script build
    volumes:
      - salary_build_folder:/frontend/build
    environment:
      - REACT_APP_PRODUCTION_URL=http://YOUR_PRODUCTION_URL:8000/
  proxy:
    build:
      context: ./nginx
    ports:
      - 8000:8080
    volumes:
      - salary_build_folder:/var/www/frontend
    depends_on:
      - back
      - front
volumes:
  salary_build_folder: