# Generated by Django 3.1.6 on 2021-03-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='TempData',
        ),
    ]
