# Generated by Django 3.1.6 on 2021-03-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_degree', models.DateField()),
                ('date_of_registration', models.DateField()),
                ('work_experience', models.DateField()),
                ('date_of_dissertation_defense', models.DateField()),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
