# Generated by Django 3.1.6 on 2021-03-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210306_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempData',
        ),
    ]
